[project]
name = "homework"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "docker>=7.1.0",
    "fastapi>=0.120.2",
    "scikit-learn==1.6.1",
    "uv>=0.9.6",
    "uvicorn>=0.38.0",
]
